repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: ^helm/.*/templates
  - id: pretty-format-json
    args: [--autofix]
  - id: trailing-whitespace
    exclude: .rs$
  - id: end-of-file-fixer
    exclude: .rs$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: ^helm/.*/templates
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    args: [--manifest-path, person/Cargo.toml]
  - id: cargo-check
    args: [--all-features, --manifest-path, person/Cargo.toml]
  - id: clippy
    args: [--all-features, --tests, --, -D, warnings, --manifest-path, person/Cargo.toml]
  - id: fmt
    args: [--manifest-path, person/Cargo.toml]
  - id: cargo-check
    args: [--all-features, --manifest-path, person/Cargo.toml]
  - id: clippy
    args: [--all-features, --tests, --, -D, warnings, --manifest-path, person/Cargo.toml]
