services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: person
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
